"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const E = require("../src/aace/demo/static/evidence.js");
const traces = JSON.parse(fs.readFileSync(0, "utf8"));
const planned = E.describe(traces.planned);
assert.match(planned.summary, /Compared 6 plans, with 3 sampled futures/);
assert.match(planned.reason, /highest recorded mission score/);
assert.doesNotMatch(planned.summary+planned.reason, /guaranteed|all possible|certainly safe/);
assert.match(E.describe(traces.direct).summary, /fixed control rule/);
assert.match(E.reason(traces.direct.candidates.find(c=>c.status==="unexplored")), /not simulated/);
assert.match(E.describe(traces.braked).reason, /controller was bypassed/);
assert.match(E.describe(traces.braked).summary, /braking request/);
assert.match(E.describe(traces.invalid).reason, /invalid.*replaced it with braking/);
assert.match(E.describe(traces.invalid).choice, /applied action was adjusted/);
assert.match(E.observed(traces.damage), /Damage occurred/);
assert.match(E.runStory(traces.finished), /Back home before the deadline/);
assert.match(E.describe(null).outcome, /appears after the move/);
assert.match(E.missions.deadline[1], /deliberately too tight/);
console.log("Recorded-evidence language checks passed.");
